import type { NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Landing from "../components/landing";
import Login from "../components/login";
/* import { trpc } from "../utils/trpc"; */

const Home: NextPage = () => {
  /* const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]); */
  const { data: session } = useSession();
    return (
      <>
      <Head>
        <title>Kengred - Shaping Communities</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { session?.user ? <Landing/> : <Login/>}
      </>
    );
  }

export default Home;